apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/your-org/gitops-repo.git  # Replace with your GitOps repo URL
    path: k8s/backend  # Path to backend deployment manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
